import { environment } from '../environments/environment.development';
const domain = environment.appurl;

export const apiurls = {
  login: domain + '/auth/login',
  buckets: domain + '/bucket/list',
  bucketsData: domain + '/bucket/get_bucket_data/',
  downloadFile: domain + '/bucket/file/download',
  forgotPass: domain + '/auth/forgot_password',
  usertype: domain + '/auth/show',
  newBucket: domain + '/api/bucket_create',
  createUser: domain + '/auth/user_create',
  allUsers: domain + '/api/user_list',
  enableuser: domain + '/api/user_status',
  addBuckets: domain + '/api/user/add_bucket',
  allGroups: domain + '/api/group_list',
  addGroup: domain + '/api/group_create',
  manageBuckets: domain + '/api/group/add_bucket',
  manageUsers: domain + '/api/group/add_users',
  changePassword: domain + '/auth/change_password',
  refreshToken: domain + '/auth/refresh_token',
  smptCreate: domain + '/auth/smtp_create',
  smptUser: domain + '/auth/get_smtp',
  testMail: domain + '/auth/test_smtp',
  folderDownload: domain + '/bucket/download_folder/',
  userLogs: domain + '/auth/user_logs',
  serverLogs: domain + '/auth/server_logs',
  applicationLogs: domain + '/auth/application_logs',
  downloadFileDup: domain + '/bucket/file/downloadfolder111',
  downloadFolderDup: domain + '/bucket/download_folder11',
  marshaCode: domain + '/auth/hotel_data',
  updateMarshaHotel: domain + '/auth/edit_hotel/',
  softwarePropertyDetails: domain + '/auth/software_property_details/',
  allSoftwares: domain + '/auth/all_softwares',
  charts: domain + '/auth/server_count_logs',
};
